name: "Generate a release package"
on:
  push:
    tags:
      - "v*"

permissions:
    contents: write

jobs:
  build:
    name: "Builds the package"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v5
        with:
         ref: "master"

      - name: "Setup NodeJS version"
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: "Generate a package-lock.json file"
        run: npm install --package-lock-only

      - name: "Install dependencies"
        run: npm ci

      - name: "Compile the project"
        run: npm run build

      - name: "Create npm package tarball"
        run: |
            npm pack --silent
            ls -alh *.tgz

      - name: "Compact the dist/Web directory contents"
        run: |
            test -d dist/Web
            cd dist/Web
            zip -r ../../dist-Web.zip .
            cd ../..
            ls -lah dist-Web.zip

      - name: "Create GitHub Release + upload assets"
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.tgz
            dist-Web.zip
          generate_release_notes: true


